name: Refresh Naukri Resume

on:
  # Runs automatically every 1 hour
  schedule:
    - cron: "0 * * * *"
  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install-deps
          npx playwright install

      - name: Run Playwright test
        run: npx playwright test
