name: Refresh Naukri Resume

on:
  schedule:
    - cron: "0 * * * *"   # every 1 hour
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install-deps
          npx playwright install

      - name: Run Playwright test in headless mode
        env:
          CI: true
          HEADLESS: true
        run: |
          npx playwright test --headed=false
